ecommerse/cartapp/urls.py
from . import views
from django.urls import path

app_name = 'cartapp'
urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('fullremove/<int:product_id>/', views.full_remove, name='full_remove'),

]

ecommerse/ecomapp/urls.py
from . import views
from django.urls import path

app_name = 'ecomapp'
urlpatterns = [

    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:p_slug>/', views.proDetail, name='prodCatDetails'),
]

ecommerse/ecommerse/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('ecomapp.urls')),
    path('searchapp/', include('searchapp.urls')),
    path('cartapp/', include('cartapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerse/searchapp/urls.py
from django.urls import path
from . import views

app_name = 'searchapp'
urlpatterns = [

    path('', views.SearchResult, name='SearchResult'),
]

ecommerse/cartapp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
from ecomapp.models import Product


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return self.cart_id




class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def Sub_Total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecommerse/ecomapp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)



    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('ecomapp:products_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)



    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('ecomapp:prodCatDetails', args=[self.category.slug, self.slug])

    def __str__(self):
        return '{}'.format(self.name)

ecommerse/searchapp/models.py
from django.db import models

# Create your models here.

ecommerse/cartapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.
from .models import Cart, CartItem
from ecomapp.models import Product


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save(),
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product, quantity=1, cart=cart)
        cart_item.save()
    return redirect('cartapp:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:

        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            sub=(cart_item.product.price * cart_item.quantity)
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter,sub=sub))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cartapp:cart_detail')


def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cartapp:cart_detail')

ecommerse/ecomapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

from .models import Product, Category
from django.core.paginator import Paginator,EmptyPage,InvalidPage

# Create your views here.


def allProdCat(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except(EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_page)


    return render(request, "category.html", {'category': c_page, 'products': products})


def proDetail(request, c_slug, p_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=p_slug)
    except Exception as e:
        raise e
    return render(request, "product.html", {'product': product})

ecommerse/searchapp/views.py
from django.shortcuts import render

# Create your views here.
from ecomapp.models import Product
from django.db.models import Q


def SearchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request, 'search.html', {'query': query, 'products': products})

ecommerse/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta CHARSET="UTF-8">
  <link rel="stylesheet" href="{% static 'css/custom.css' %}">
  <link href="https://fonts.googleapis.com/css2?family=Merriweather:ital@1&display=swap" rel="stylesheet">
<script src=" https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<meta name="description" content="{% block metadescription %}{% endblock %}">

<title>

  {% block title %}{% endblock %}



</title></head>

<body>

  <div class="container">


    {% include 'header.html' %}

    {% include 'navbar.html' %}



     {% block content %}
    {% endblock %}

  </div>
 {% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

ecommerse/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    This is the Cart page.Proceed to review your items $ place Order
{% endblock %}

{% block title %}
  Cart-Pink Store PVT LTD
{% endblock %}

{% block content %}
{% if not cart_items %}

  <div>
    <div class="text-center">
    <h1 class="text-center my_title">
      Your Shopping Cart is EMPTY

    </h1><br>
      <p class="text-center">
        Please Click <a href="{% url 'ecomapp:allProdCat' %}">here</a>To Continue Shopping...
      </p>
      </div>
  </div>
{% else %}
    <div>
        <div class="text-center">
<br>
        <h1 class="text-center my_title">Your Shopping Cart</h1>

<br>
    </div>
        </div>
<div class="row mx-auto">
  <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
    <table class="table my_custom_table">
      <thead class="my_custom_thead">
      <tr>
        <th colspan="5">
          Your Items

        </th>
      </tr>
      </thead>
      <tbody>
      {% for cart_item in cart_items %}
          <tr>
            <td>
              <a href="{% url 'cartapp:cart_detail' %}"><img src="{{cart_item.product.image.url}}" alt="{{cart_item}}" class="float-left rounded custom_image" width="100px" height="100px"></a>
            </td>
            <td class="text-left">
              {{cart_item.product.name}}<br>
              SKU : {{cart_item.product.id}}<br>

              Price : {{cart_item.product.price}}
              <br>


              QTY :{{cart_item.quantity}} *  {{cart_item}}
              <br>
            total price for  {{cart_item}} :${{cart_item.Sub_Total}}
</td>
            {% if cart_item.quantity < cart_item.product.stock %}
            <td>
              <a href="{% url 'cartapp:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa fa-plus custom_icon"></i></a>&nbsp;<br>
              <a href="{% url 'cartapp:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>&nbsp;<br>
              <a href="{% url 'cartapp:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i></a>&nbsp;<br>

            </td>
           {% else %}
             <td>

              <a href="{% url 'cartapp:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>&nbsp;<br>
              <a href="{% url 'cartapp:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i></a>&nbsp;<br>

            </td>
            {% endif %}
          </tr>
      {% endfor %}
      </tbody>
    </table>

  </div>

    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">

      <table class="table my_custom_table">
        <thead class="my_custom_thead">
        <tr>
          <th>
            CHECKOUT
          </th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>
            Please review your Shopping cart items before proceeding payment
          </td>
        </tr>
        <tr><td class="text-center">Total price :<strong>{{total}}</strong></td> </tr>
        </tbody>

      </table>

      <div class="mx-auto">
        <a href="{% url 'ecomapp:allProdCat' %}" class="btn btn-secondary  my_custom_button">Continue Shopping</a>
        &nbsp;<a href="{% url 'ecomapp:allProdCat' %}" class="btn btn-secondary  my_custom_button"> Payment</a>



          </div>

{% endif %}
    </div>
  </div>
{% endblock %}

ecommerse/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  {% if category %}
    {{category.description|truncatewords:155 }}
  {% else %}
   Welcome to Pink Cart Store Where you can buy different items ....
  {% endif %}
{% endblock %}

{% block title %}
{% if category %}
    {{category.name}} -Pink Store
{% else %}
    See our New collections-Pink Store
{% endif %}
{% endblock %}


{% block content %}
{% if category %}
 <div>
     <div class="row my_row_class">


           <p  style="font-size:22px;margin-left:40%; " >  <a class="text-center link" href="{% url 'ecomapp:allProdCat' %}">Our Products Collections </p></a>


     </div>
 </div>
{% endif %}


<div class="mx_auto">
    <div>
    {% if category %}
    <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}"><br>
    </div>
    <div><h1 class="text-center my-title">
        {{category.name}}
    </h1>
        <p class="text-justify">{{category.description}}</p>
    </div>
   
    {% else %}

          <img class="my_image my-image-padding" src="{% static 'img/banner1.png' %}" alt="our products" >

   <br><br>

<div>
    <h1 class="text-center my-title" >
        Our Product Collections
    </h1>
     <p class="text-justify my-p " > New Trends in Clothes. High Quality, Up to 85% Off. Free Shipping Available! A Great Selection of Clothes.Women's Fashion Clothes - Buy Ladies Clothing, Shoes & Footwear, Bags, Sunglasses, Watches etc Online in Nepal. | Thulo.com Women's Fashion Shop by Category Shop by Category Search Filters Featured Vendors Sazuna jewels Of Nepal Jagannath Traders NAVIGATE Veerjara OUXI Classic Collection XimiVogue Karki & Murphy handicrafts Perla KTM CTY</p>
</div>
    {% endif %}
<div class="container">
    <div class="row mx_auto">
        {% for product in products %}
        <div class="my-bottom-margin col-9 col-sm-4 col-md-4  xol-lg-4">

            <div class="card text-center" style="min-width:18rem">
                <a href="{{product.get_url}}"> <img class="card-img-top my-image" src="{{product.image.url}}" alt="{{product.name}}" height="150px" width="150px"></a>
                <div class="card-body">

                        <h4>{{product.name}}</h4>
                        <p>{{product.price}}</p>

                    </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx_auto">
        {% if products.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}} </a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>

{% endblock %}

ecommerse/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
  <p class="text-center" align="center">
    @Copyright : TechOne Solution Pvt Ltd . All Rights Reserved
  </p>
</div>

ecommerse/templates/header.html
{% load static %}
<header>
    <center><a href="{% url 'ecomapp:allProdCat' %}"> <image src=" {% static 'img/1.jpg' %}" alt="logoimage" align="center" height="250px" width="250px"></image></center>
</a>
</header>

ecommerse/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark
                        justify-content-between text-white"
                 style="background-color: purple;">
<div class="container-fluid" >
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
<li class="nav-item ">
        <a class="nav-link" href="#">Home </a>
      </li>

      <li class="nav-item dropdown {% if 'ecomapp' in request.path %} active {% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          shop
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'ecomapp:allProdCat' %}">All products</a>
            {% for cat in links %}
          <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
              {% endfor %}
        </ul>
      </li>
        {% if item_count > 0 %}
        <li class="nav-item">
        <a class="nav-link" href="{% url 'cartapp:cart_detail' %}" ><i class="fa fa-shopping-cart"></i>{{item_count}}</a>
      </li>
        {% endif %}
    </ul>
      </div>
      <form class="d-flex" action="{% url 'searchapp:SearchResult' %}" method="get">
          {% csrf_token %}
      <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
      <button class="btn btn-outline-success " type="submit"><i class="fa fa-search "></i></button>
    </form>
  </div>
</div>
</nav>

ecommerse/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

    {{product.description|truncatewords:155 }}



{% endblock %}

{% block title %}
{% if category %}
    {{product.name}} -Pink Store

{% endif %}
{% endblock %}


{% block content %}

<div class="row my_prod_row_class">
  <div class="mx_auto">
  <p>  <a href="{% url 'ecomapp:allProdCat' %}">Home</a>|<a href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}}

  </p>

</div >
<div class="container">
<br>

<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img src="{{product.image.url}}" alt="{{product.name}}" width="300" height="250px">
        </div>
    </div>


        <div class="col-12 col-sm-12 col-md-12 col-lg-6 ">
            <div>
            <h1 class="my_prod_title">{{product.name}}</h1>
                <p>
                ${{product.price}}
            </p>
            <p class="my_title"><b>PRODUCT DESCRIPTION</b></p>
             <p class="text-justify my_prod_text">
                {{product.description}}
            </p>



{% if product.stock <= 0 %}
    <p class="text-justify my_prod_text"><b>Out Of Stock</b></p>
{% else %}
    <a class="btn btn-secondary" href="{% url 'cartapp:add_cart' product.id %}">Add To Cart</a>
{% endif %}
         </div>
        </div>
    </div>
</div>
    </div>
{% endblock %}

ecommerse/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    We Have Variety Of Products
{% endblock %}

{% block title %}
  Search
{% endblock %}

{% block content %}

<div>
  <p class="text-center my_search_text">
      You Have Searched For : <b>{{query}}</b>
  </p>
</div>
<div class="container">
    <div class="row mx_auto">
        {% for product in products %}
        <div class="my-bottom-margin col-9 col-sm-4 col-md-4  xol-lg-4">

            <div class="card text-center" style="min-width:18rem">

                <div class="card-body" style="width:250px;">
                        <a href="{{product.get_url}}"> <img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}" height="100px" width="100px" align="center"></a>

                        <h4>{{product.name}}</h4>
                        <p>{{product.price}}</p>

                    </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx_auto">
            <p class="text-center my_search_text">
                No Result Found
            </p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}